using System.Collections.Generic;

namespace Crosswords.Services.Catalogs
{
    public class PeriodicTableCatalog : ICatalog
    {
        private readonly Dictionary<string, string> _elements = new Dictionary<string, string>()
        {
            {"H", "vodík"},
            {"He", "helium"},
            {"Li", "lithium"},
            {"Be", "beryllium"},
            {"B", "bor"},
            {"C", "uhlík"},
            {"N", "dusík"},
            {"O", "kyslík"},
            {"F", "fluor"},
            {"Ne", "neon"},
            {"Na", "sodík"},
            {"Mg", "hořčík"},
            {"Al", "hliník"},
            {"Si", "křemík"},
            {"P", "fosfor"},
            {"S", "síra"},
            {"Cl", "chlor"},
            {"Ar", "argon"},
            {"K", "draslík"},
            {"Ca", "vápník"},
            {"Sc", "skandium"},
            {"Ti", "titan"},
            {"V", "vanad"},
            {"Cr", "chrom"},
            {"Mn", "mangan"},
            {"Fe", "železo"},
            {"Co", "kobalt"},
            {"Ni", "nikl"},
            {"Cu", "měď"},
            {"Zn", "zinek"},
            {"Ga", "gallium"},
            {"Ge", "germanium"},
            {"As", "arsen"},
            {"Se", "selen"},
            {"Br", "brom"},
            {"Kr", "krypton"},
            {"Rb", "rubidium"},
            {"Sr", "stroncium"},
            {"Y", "yttrium"},
            {"Zr", "zirkonium"},
            {"Nb", "niob"},
            {"Mo", "molybden"},
            {"Tc", "technecium"},
            {"Ru", "ruthenium"},
            {"Rh", "rhodium"},
            {"Pd", "palladium"},
            {"Ag", "stříbro"},
            {"Cd", "kadmium"},
            {"In", "indium"},
            {"Sn", "cín"},
            {"Sb", "antimon"},
            {"Te", "tellur"},
            {"I", "jod"},
            {"Xe", "xenon"},
            {"Cs", "cesium"},
            {"Ba", "baryum"},
            {"La", "lanthan"},
            {"Ce", "cer"},
            {"Pr", "praseodym"},
            {"Nd", "neodym"},
            {"Pm", "promethium"},
            {"Sm", "samarium"},
            {"Eu", "europium"},
            {"Gd", "gadolinium"},
            {"Tb", "terbium"},
            {"Dy", "dysprosium"},
            {"Ho", "holmium"},
            {"Er", "erbium"},
            {"Tm", "thulium"},
            {"Yb", "ytterbium"},
            {"Lu", "lutecium"},
            {"Hf", "hafnium"},
            {"Ta", "tantal"},
            {"W", "wolfram"},
            {"Re", "rhenium"},
            {"Os", "osmium"},
            {"Ir", "iridium"},
            {"Pt", "platina"},
            {"Au", "zlato"},
            {"Hg", "rtuť"},
            {"Tl", "thallium"},
            {"Pb", "olovo"},
            {"Bi", "bismut"},
            {"Po", "polonium"},
            {"At", "astat"},
            {"Rn", "radon"},
            {"Fr", "francium"},
            {"Ra", "radium"},
            {"Ac", "aktinium"},
            {"Th", "thorium"},
            {"Pa", "protaktinium"},
            {"U", "uran"},
            {"Np", "neptunium"},
            {"Pu", "plutonium"},
            {"Am", "americium"},
            {"Cm", "curium"},
            {"Bk", "berkelium"},
            {"Cf", "kalifornium"},
            {"Es", "einsteinium"},
            {"Fm", "fermium"},
            {"Md", "mendelevium"},
            {"No", "nobelium"},
            {"Lr", "lawrencium"},
            {"Rf", "rutherfordium"},
            {"Db", "dubnium"},
            {"Sg", "seaborgium"},
            {"Bh", "bohrium"},
            {"Hs", "hassium"},
            {"Mt", "meitnerium"},
            {"Ds", "darmstadtium"},
            {"Rg", "roentgenium"},
            {"Cn", "kopernicium"},
            {"Nh", "nihonium"},
            {"Fl", "flerovium"},
            {"Mc", "moscovium"},
            {"Lv", "livermorium"},
            {"Ts", "tennessin"},
            {"Og", "oganesson"}
        };


        public string? GetLabel(string word)
        {
            return _elements.ContainsKey(word) ? $"Chemická značka pro {_elements[word]}" : null;
        }
    }
}